---
name: catalog-info

on:
  pull_request:
    branches:
      - main
    paths:
      - 'catalog-info.yaml'

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: elastic/oblt-actions/elastic/validate-catalog@98afc1bbd3c6fefd6bf6a9995ccbcc37d68c5a22 # v1

