---
name: catalog-info

on:
  pull_request:
    branches:
      - main
    paths:
      - 'catalog-info.yaml'

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - uses: elastic/oblt-actions/elastic/validate-catalog@e1273cafad946cd6255c5c3ade06cce92ea77e33 # v1

