---
name: catalog-info

on:
  pull_request:
    branches:
      - main
    paths:
      - 'catalog-info.yaml'

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - uses: elastic/oblt-actions/elastic/validate-catalog@f41c574f90f4ad4531081f0562e1f94ceb572b7a # v1

